// Code generated by MockGen. DO NOT EDIT.
// Source: ./libs/vclient/ivclient/vclient.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	vclient "github.com/velo-protocol/DRSv2/go/libs/vclient"
	reflect "reflect"
)

// MockVClient is a mock of VClient interface
type MockVClient struct {
	ctrl     *gomock.Controller
	recorder *MockVClientMockRecorder
}

// MockVClientMockRecorder is the mock recorder for MockVClient
type MockVClientMockRecorder struct {
	mock *MockVClient
}

// NewMockVClient creates a new mock instance
func NewMockVClient(ctrl *gomock.Controller) *MockVClient {
	mock := &MockVClient{ctrl: ctrl}
	mock.recorder = &MockVClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockVClient) EXPECT() *MockVClientMockRecorder {
	return m.recorder
}

// SetupCredit mocks base method
func (m *MockVClient) SetupCredit(ctx context.Context, input *vclient.SetupCreditInput) (*vclient.SetupCreditOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupCredit", ctx, input)
	ret0, _ := ret[0].(*vclient.SetupCreditOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupCredit indicates an expected call of SetupCredit
func (mr *MockVClientMockRecorder) SetupCredit(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupCredit", reflect.TypeOf((*MockVClient)(nil).SetupCredit), ctx, input)
}

// MintByCollateralAmount mocks base method
func (m *MockVClient) MintFromCollateralAmount(ctx context.Context, input *vclient.MintByCollateralAmountInput) (*vclient.MintByCollateralAmountCreditOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MintByCollateralAmount", ctx, input)
	ret0, _ := ret[0].(*vclient.MintByCollateralAmountCreditOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MintByCollateralAmount indicates an expected call of MintByCollateralAmount
func (mr *MockVClientMockRecorder) MintByCollateralAmount(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MintByCollateralAmount", reflect.TypeOf((*MockVClient)(nil).MintFromCollateralAmount), ctx, input)
}

// MintFromStableCreditAmount mocks base method
func (m *MockVClient) MintFromStableCreditAmount(ctx context.Context, input *vclient.MintFromStableCreditAmountInput) (*vclient.MintFromStableCreditAmountCreditOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MintFromStableCreditAmount", ctx, input)
	ret0, _ := ret[0].(*vclient.MintFromStableCreditAmountCreditOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MintFromStableCreditAmount indicates an expected call of MintFromStableCreditAmount
func (mr *MockVClientMockRecorder) MintFromStableCreditAmount(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MintFromStableCreditAmount", reflect.TypeOf((*MockVClient)(nil).MintFromStableCreditAmount), ctx, input)
}
