// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gate.proto

package gate

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DepositRequest struct {
	HashLock             string   `protobuf:"bytes,1,opt,name=hashLock,proto3" json:"hashLock,omitempty"`
	DrsAddress           string   `protobuf:"bytes,2,opt,name=drsAddress,proto3" json:"drsAddress,omitempty"`
	StellarAddress       string   `protobuf:"bytes,3,opt,name=stellarAddress,proto3" json:"stellarAddress,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetCode            string   `protobuf:"bytes,5,opt,name=assetCode,proto3" json:"assetCode,omitempty"`
	AssetIssuer          string   `protobuf:"bytes,6,opt,name=assetIssuer,proto3" json:"assetIssuer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{0}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetHashLock() string {
	if m != nil {
		return m.HashLock
	}
	return ""
}

func (m *DepositRequest) GetDrsAddress() string {
	if m != nil {
		return m.DrsAddress
	}
	return ""
}

func (m *DepositRequest) GetStellarAddress() string {
	if m != nil {
		return m.StellarAddress
	}
	return ""
}

func (m *DepositRequest) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DepositRequest) GetAssetCode() string {
	if m != nil {
		return m.AssetCode
	}
	return ""
}

func (m *DepositRequest) GetAssetIssuer() string {
	if m != nil {
		return m.AssetIssuer
	}
	return ""
}

type SubmitDepositResponse struct {
	DepositAddress       string   `protobuf:"bytes,1,opt,name=depositAddress,proto3" json:"depositAddress,omitempty"`
	RefundTxeB64         string   `protobuf:"bytes,2,opt,name=refundTxeB64,proto3" json:"refundTxeB64,omitempty"`
	DeleteTxeB64         string   `protobuf:"bytes,3,opt,name=deleteTxeB64,proto3" json:"deleteTxeB64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitDepositResponse) Reset()         { *m = SubmitDepositResponse{} }
func (m *SubmitDepositResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitDepositResponse) ProtoMessage()    {}
func (*SubmitDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{1}
}

func (m *SubmitDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitDepositResponse.Unmarshal(m, b)
}
func (m *SubmitDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitDepositResponse.Marshal(b, m, deterministic)
}
func (m *SubmitDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitDepositResponse.Merge(m, src)
}
func (m *SubmitDepositResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitDepositResponse.Size(m)
}
func (m *SubmitDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitDepositResponse proto.InternalMessageInfo

func (m *SubmitDepositResponse) GetDepositAddress() string {
	if m != nil {
		return m.DepositAddress
	}
	return ""
}

func (m *SubmitDepositResponse) GetRefundTxeB64() string {
	if m != nil {
		return m.RefundTxeB64
	}
	return ""
}

func (m *SubmitDepositResponse) GetDeleteTxeB64() string {
	if m != nil {
		return m.DeleteTxeB64
	}
	return ""
}

type CommitDepositRequest struct {
	SignedTx                  string   `protobuf:"bytes,1,opt,name=signedTx,proto3" json:"signedTx,omitempty"`
	SmartContractChainAddress string   `protobuf:"bytes,2,opt,name=smartContractChainAddress,proto3" json:"smartContractChainAddress,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *CommitDepositRequest) Reset()         { *m = CommitDepositRequest{} }
func (m *CommitDepositRequest) String() string { return proto.CompactTextString(m) }
func (*CommitDepositRequest) ProtoMessage()    {}
func (*CommitDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{2}
}

func (m *CommitDepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitDepositRequest.Unmarshal(m, b)
}
func (m *CommitDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitDepositRequest.Marshal(b, m, deterministic)
}
func (m *CommitDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitDepositRequest.Merge(m, src)
}
func (m *CommitDepositRequest) XXX_Size() int {
	return xxx_messageInfo_CommitDepositRequest.Size(m)
}
func (m *CommitDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitDepositRequest proto.InternalMessageInfo

func (m *CommitDepositRequest) GetSignedTx() string {
	if m != nil {
		return m.SignedTx
	}
	return ""
}

func (m *CommitDepositRequest) GetSmartContractChainAddress() string {
	if m != nil {
		return m.SmartContractChainAddress
	}
	return ""
}

type CommitDepositResponse struct {
	StellarTxHash        string   `protobuf:"bytes,1,opt,name=stellarTxHash,proto3" json:"stellarTxHash,omitempty"`
	SmartContractTxHash  string   `protobuf:"bytes,2,opt,name=SmartContractTxHash,proto3" json:"SmartContractTxHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitDepositResponse) Reset()         { *m = CommitDepositResponse{} }
func (m *CommitDepositResponse) String() string { return proto.CompactTextString(m) }
func (*CommitDepositResponse) ProtoMessage()    {}
func (*CommitDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_743bb58a714d8b7d, []int{3}
}

func (m *CommitDepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitDepositResponse.Unmarshal(m, b)
}
func (m *CommitDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitDepositResponse.Marshal(b, m, deterministic)
}
func (m *CommitDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitDepositResponse.Merge(m, src)
}
func (m *CommitDepositResponse) XXX_Size() int {
	return xxx_messageInfo_CommitDepositResponse.Size(m)
}
func (m *CommitDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitDepositResponse proto.InternalMessageInfo

func (m *CommitDepositResponse) GetStellarTxHash() string {
	if m != nil {
		return m.StellarTxHash
	}
	return ""
}

func (m *CommitDepositResponse) GetSmartContractTxHash() string {
	if m != nil {
		return m.SmartContractTxHash
	}
	return ""
}

func init() {
	proto.RegisterType((*DepositRequest)(nil), "gate.DepositRequest")
	proto.RegisterType((*SubmitDepositResponse)(nil), "gate.SubmitDepositResponse")
	proto.RegisterType((*CommitDepositRequest)(nil), "gate.CommitDepositRequest")
	proto.RegisterType((*CommitDepositResponse)(nil), "gate.CommitDepositResponse")
}

func init() { proto.RegisterFile("gate.proto", fileDescriptor_743bb58a714d8b7d) }

var fileDescriptor_743bb58a714d8b7d = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xe9, 0xf7, 0x21, 0x91, 0xab, 0xb0, 0x18, 0xc1, 0x54, 0x34, 0x86, 0x34, 0xc6, 0xb8,
	0x22, 0x46, 0x8d, 0x2b, 0x37, 0x5a, 0x13, 0xff, 0xae, 0x80, 0x17, 0x18, 0x98, 0x2b, 0x6d, 0xa4,
	0x9d, 0x3a, 0x77, 0x9a, 0xf0, 0x06, 0x3e, 0x86, 0x2f, 0xe4, 0x43, 0x19, 0xa6, 0x53, 0x6c, 0x9b,
	0xba, 0xeb, 0xfd, 0x9d, 0x93, 0x99, 0x7b, 0x4e, 0x07, 0x60, 0xc1, 0x35, 0x8e, 0x12, 0x25, 0xb5,
	0x64, 0xcd, 0xf5, 0xb7, 0xf7, 0xed, 0x40, 0xf7, 0x1e, 0x13, 0x49, 0xa1, 0x1e, 0xe3, 0x47, 0x8a,
	0xa4, 0xd9, 0x00, 0xb6, 0x03, 0x4e, 0xc1, 0xab, 0x9c, 0xbf, 0xbb, 0xce, 0xd0, 0x39, 0x6b, 0x8f,
	0x37, 0x33, 0x3b, 0x06, 0x10, 0x8a, 0x6e, 0x85, 0x50, 0x48, 0xe4, 0xfe, 0x33, 0x6a, 0x81, 0xb0,
	0x53, 0xe8, 0x92, 0xc6, 0xe5, 0x92, 0xab, 0xdc, 0xf3, 0xdf, 0x78, 0x2a, 0x94, 0xed, 0x43, 0x8b,
	0x47, 0x32, 0x8d, 0xb5, 0xdb, 0x34, 0xba, 0x9d, 0xd8, 0x11, 0xb4, 0x39, 0x11, 0x6a, 0x5f, 0x0a,
	0x74, 0xb7, 0x8c, 0xf4, 0x0b, 0xd8, 0x10, 0x76, 0xcc, 0xf0, 0x44, 0x94, 0xa2, 0x72, 0x5b, 0x46,
	0x2f, 0x22, 0xef, 0xd3, 0x81, 0xfe, 0x24, 0x9d, 0x45, 0xa1, 0xde, 0x84, 0xa2, 0x44, 0xc6, 0x84,
	0xeb, 0xcd, 0x44, 0x86, 0xf2, 0xcd, 0xb2, 0x6c, 0x15, 0xca, 0x3c, 0xd8, 0x55, 0xf8, 0x96, 0xc6,
	0x62, 0xba, 0xc2, 0xbb, 0xeb, 0x2b, 0x9b, 0xb1, 0xc4, 0xd6, 0x1e, 0x81, 0x4b, 0xd4, 0x68, 0x3d,
	0x59, 0xc6, 0x12, 0xf3, 0x12, 0xe8, 0xf9, 0x32, 0x2a, 0x2e, 0xb2, 0x69, 0x97, 0xc2, 0x45, 0x8c,
	0x62, 0xba, 0xca, 0xdb, 0xcd, 0x67, 0x76, 0x03, 0x07, 0x14, 0x71, 0xa5, 0x7d, 0x19, 0x6b, 0xc5,
	0xe7, 0xda, 0x0f, 0x78, 0x18, 0x97, 0xcb, 0xfe, 0xdb, 0xe0, 0x49, 0xe8, 0x57, 0x6e, 0xb4, 0xd1,
	0x4f, 0xa0, 0x63, 0xeb, 0x9f, 0xae, 0x1e, 0x39, 0x05, 0xf6, 0xde, 0x32, 0x64, 0xe7, 0xb0, 0x37,
	0x29, 0x9e, 0x6d, 0xbd, 0xd9, 0xb5, 0x75, 0xd2, 0xc5, 0x97, 0x03, 0xcd, 0x07, 0xae, 0x91, 0xbd,
	0x40, 0xaf, 0x52, 0x7a, 0x96, 0xb5, 0x37, 0x32, 0xef, 0xad, 0x4c, 0x07, 0x87, 0x19, 0xad, 0xfd,
	0x4d, 0x5e, 0x83, 0x3d, 0x43, 0xa7, 0x14, 0x83, 0x0d, 0x32, 0x7f, 0x5d, 0x9b, 0xf9, 0x59, 0xb5,
	0xb9, 0xbd, 0xc6, 0xac, 0x65, 0x9e, 0xfa, 0xe5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x93,
	0xe3, 0x7a, 0xf8, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GateClient is the client API for Gate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GateClient interface {
	SubmitDepositRequest(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*SubmitDepositResponse, error)
	CommitDeposit(ctx context.Context, in *CommitDepositRequest, opts ...grpc.CallOption) (*CommitDepositResponse, error)
}

type gateClient struct {
	cc *grpc.ClientConn
}

func NewGateClient(cc *grpc.ClientConn) GateClient {
	return &gateClient{cc}
}

func (c *gateClient) SubmitDepositRequest(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*SubmitDepositResponse, error) {
	out := new(SubmitDepositResponse)
	err := c.cc.Invoke(ctx, "/gate.Gate/SubmitDepositRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateClient) CommitDeposit(ctx context.Context, in *CommitDepositRequest, opts ...grpc.CallOption) (*CommitDepositResponse, error) {
	out := new(CommitDepositResponse)
	err := c.cc.Invoke(ctx, "/gate.Gate/CommitDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateServer is the server API for Gate service.
type GateServer interface {
	SubmitDepositRequest(context.Context, *DepositRequest) (*SubmitDepositResponse, error)
	CommitDeposit(context.Context, *CommitDepositRequest) (*CommitDepositResponse, error)
}

func RegisterGateServer(s *grpc.Server, srv GateServer) {
	s.RegisterService(&_Gate_serviceDesc, srv)
}

func _Gate_SubmitDepositRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).SubmitDepositRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gate.Gate/SubmitDepositRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).SubmitDepositRequest(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gate_CommitDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateServer).CommitDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gate.Gate/CommitDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateServer).CommitDeposit(ctx, req.(*CommitDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gate.Gate",
	HandlerType: (*GateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitDepositRequest",
			Handler:    _Gate_SubmitDepositRequest_Handler,
		},
		{
			MethodName: "CommitDeposit",
			Handler:    _Gate_CommitDeposit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gate.proto",
}
